# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/GameOfCodesProject/GameOfCodes/GameOfCodes.cache/wt [current_project]
set_property parent.project_path F:/GameOfCodesProject/GameOfCodes/GameOfCodes.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  F:/Ready_Modules/stepmotor.sv
  F:/Ready_Modules/steppermotor_wrapper.sv
  F:/GameOfCodesProject/GameOfCodes/GameOfCodes.srcs/sources_1/new/ShiftOrder.sv
  F:/Ready_Modules/SevSeg_4digit.sv
  F:/GameOfCodesProject/GameOfCodes/GameOfCodes.srcs/sources_1/new/ScoreCounter.sv
  F:/GameOfCodesProject/GameOfCodes/GameOfCodes.srcs/sources_1/new/MappingTableKeyRegister.sv
  F:/Ready_Modules/keypad4X4.sv
  F:/GameOfCodesProject/GameOfCodes/GameOfCodes.srcs/sources_1/new/KeyInputCodeComparator.sv
  F:/GameOfCodesProject/GameOfCodes/GameOfCodes.srcs/sources_1/new/GameState.sv
  F:/GameOfCodesProject/GameOfCodes/GameOfCodes.srcs/sources_1/new/RandomGenerator.sv
  F:/GameOfCodesProject/GameOfCodes/GameOfCodes.srcs/sources_1/new/GameOfCodes.sv
}
read_xdc F:/GameOfCodesProject/GameOfCodes/GameOfCodes.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files F:/GameOfCodesProject/GameOfCodes/GameOfCodes.srcs/constrs_1/new/cons.xdc]

synth_design -top GameOfCodes -part xc7a35tcpg236-1
write_checkpoint -noxdef GameOfCodes.dcp
catch { report_utilization -file GameOfCodes_utilization_synth.rpt -pb GameOfCodes_utilization_synth.pb }
